import './globals.css'
import type { Metadata } from 'next';
import SideBar from '@/components/SideBar';
import { SessionProvider } from '@/components/SessionProvider';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import Login from '@/components/Login';

export const metadata: Metadata = {
  title: 'ChatGPT Clone',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <head />
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className='flex'>
              {/* Sidebar */}
              <div className='bg-[#202123] md:min-w-[20rem] max-w-xs overflow-y-auto h-screen'>
                <SideBar />
              </div>

              {/* Client Provider - Notification */}

              <div className='bg-[#343541] flex-1'>{children}</div>
            </div>
          )}
        </SessionProvider>

      </body>
    </html>
  )
}
